fragment NotesParts on Notes {
  __typename
  body
  tags
  published
  updated
}

fragment ReviewsParts on Reviews {
  __typename
  topic
  body
  tags
  url
  image
  published
  updated
}

fragment PhotosParts on Photos {
  __typename
  body
  tags
  image
  location
  camera
  published
  updated
}
